export const eventCategories = [
  'All',
  'Business',
  'Entertainment',
  'Education',
  'Food and Drink',
  'Game',
  'Health',
  'Hobbies',
  'Lifestyle',
  'Music',
  'Science and Technology',
  'Seminars',
  'Sports',
  'Travel',
  'Webinars',
];
